version: '3.8'

services:
  db:
    image: docker.io/library/postgres:16-alpine
    container_name: bingo-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bingo
    ports:
      - "5432:5432"
    volumes:
      - bingo_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  bingo_pgdata:
